# edusync-spring-backend/src/main/resources/application.properties

server.port=8090

# MongoDB — dedicated quiz database
spring.data.mongodb.uri=mongodb://localhost:27017/edusync_quiz
spring.data.mongodb.database=edusync_quiz

spring.application.name=edusync-spring-backend

# Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.edusync=DEBUG